version: '3.9'

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5673:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - tweetNet


  tweet-api:
    build: .
    depends_on:
      rabbit:
        condition: service_healthy
    ports:
      - 8087:8087
    networks:
      - tweetNet

networks:
  tweetNet:
    name: tweetNet
    driver: bridge