// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: proto/goal.proto

package goal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *UserId) Reset() {
	*x = UserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{0}
}

func (x *UserId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BudgetSummaryItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string  `protobuf:"bytes,6,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CategoryId   string  `protobuf:"bytes,1,opt,name=CategoryId,proto3" json:"CategoryId,omitempty"`
	TotalAmount  float32 `protobuf:"fixed32,2,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	StartingTime string  `protobuf:"bytes,3,opt,name=StartingTime,proto3" json:"StartingTime,omitempty"`
	EndingTime   string  `protobuf:"bytes,4,opt,name=EndingTime,proto3" json:"EndingTime,omitempty"`
	Period       string  `protobuf:"bytes,5,opt,name=Period,proto3" json:"Period,omitempty"`
}

func (x *BudgetSummaryItem) Reset() {
	*x = BudgetSummaryItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BudgetSummaryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetSummaryItem) ProtoMessage() {}

func (x *BudgetSummaryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetSummaryItem.ProtoReflect.Descriptor instead.
func (*BudgetSummaryItem) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{1}
}

func (x *BudgetSummaryItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BudgetSummaryItem) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *BudgetSummaryItem) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *BudgetSummaryItem) GetStartingTime() string {
	if x != nil {
		return x.StartingTime
	}
	return ""
}

func (x *BudgetSummaryItem) GetEndingTime() string {
	if x != nil {
		return x.EndingTime
	}
	return ""
}

func (x *BudgetSummaryItem) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetUserBudgetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*BudgetSummaryItem `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *GetUserBudgetResponse) Reset() {
	*x = GetUserBudgetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBudgetResponse) ProtoMessage() {}

func (x *GetUserBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBudgetResponse.ProtoReflect.Descriptor instead.
func (*GetUserBudgetResponse) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserBudgetResponse) GetResults() []*BudgetSummaryItem {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetUserMoneyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	StartingTime string `protobuf:"bytes,2,opt,name=StartingTime,proto3" json:"StartingTime,omitempty"`
	EndingTime   string `protobuf:"bytes,3,opt,name=EndingTime,proto3" json:"EndingTime,omitempty"`
}

func (x *GetUserMoneyRequest) Reset() {
	*x = GetUserMoneyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMoneyRequest) ProtoMessage() {}

func (x *GetUserMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMoneyRequest.ProtoReflect.Descriptor instead.
func (*GetUserMoneyRequest) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserMoneyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserMoneyRequest) GetStartingTime() string {
	if x != nil {
		return x.StartingTime
	}
	return ""
}

func (x *GetUserMoneyRequest) GetEndingTime() string {
	if x != nil {
		return x.EndingTime
	}
	return ""
}

type GetUserMoneyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryId  string  `protobuf:"bytes,1,opt,name=CategoryId,proto3" json:"CategoryId,omitempty"`
	TotalAmount float32 `protobuf:"fixed32,2,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	Time        string  `protobuf:"bytes,3,opt,name=Time,proto3" json:"Time,omitempty"`
}

func (x *GetUserMoneyResponse) Reset() {
	*x = GetUserMoneyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMoneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMoneyResponse) ProtoMessage() {}

func (x *GetUserMoneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMoneyResponse.ProtoReflect.Descriptor instead.
func (*GetUserMoneyResponse) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserMoneyResponse) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *GetUserMoneyResponse) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetUserMoneyResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type GoalProgressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	StartingTime string `protobuf:"bytes,2,opt,name=StartingTime,proto3" json:"StartingTime,omitempty"`
	EndingTime   string `protobuf:"bytes,3,opt,name=EndingTime,proto3" json:"EndingTime,omitempty"`
}

func (x *GoalProgressRequest) Reset() {
	*x = GoalProgressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoalProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalProgressRequest) ProtoMessage() {}

func (x *GoalProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalProgressRequest.ProtoReflect.Descriptor instead.
func (*GoalProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{5}
}

func (x *GoalProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GoalProgressRequest) GetStartingTime() string {
	if x != nil {
		return x.StartingTime
	}
	return ""
}

func (x *GoalProgressRequest) GetEndingTime() string {
	if x != nil {
		return x.EndingTime
	}
	return ""
}

type GoalProgressItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status        string  `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	TargetAmount  float32 `protobuf:"fixed32,2,opt,name=TargetAmount,proto3" json:"TargetAmount,omitempty"`
	CurrentAmount float32 `protobuf:"fixed32,3,opt,name=CurrentAmount,proto3" json:"CurrentAmount,omitempty"`
	TotalAmount   float32 `protobuf:"fixed32,4,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
}

func (x *GoalProgressItem) Reset() {
	*x = GoalProgressItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoalProgressItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalProgressItem) ProtoMessage() {}

func (x *GoalProgressItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalProgressItem.ProtoReflect.Descriptor instead.
func (*GoalProgressItem) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{6}
}

func (x *GoalProgressItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GoalProgressItem) GetTargetAmount() float32 {
	if x != nil {
		return x.TargetAmount
	}
	return 0
}

func (x *GoalProgressItem) GetCurrentAmount() float32 {
	if x != nil {
		return x.CurrentAmount
	}
	return 0
}

func (x *GoalProgressItem) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type GoalProgressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*GoalProgressItem `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *GoalProgressResponse) Reset() {
	*x = GoalProgressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoalProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalProgressResponse) ProtoMessage() {}

func (x *GoalProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalProgressResponse.ProtoReflect.Descriptor instead.
func (*GoalProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{7}
}

func (x *GoalProgressResponse) GetResults() []*GoalProgressItem {
	if x != nil {
		return x.Results
	}
	return nil
}

type Void3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void3) Reset() {
	*x = Void3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void3) ProtoMessage() {}

func (x *Void3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void3.ProtoReflect.Descriptor instead.
func (*Void3) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{8}
}

type GoalResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TargetAmount  string `protobuf:"bytes,3,opt,name=target_amount,json=targetAmount,proto3" json:"target_amount,omitempty"`
	CurrentAmount string `protobuf:"bytes,4,opt,name=current_amount,json=currentAmount,proto3" json:"current_amount,omitempty"`
	Deadline      string `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	CreatedAt     string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *GoalResp) Reset() {
	*x = GoalResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalResp) ProtoMessage() {}

func (x *GoalResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalResp.ProtoReflect.Descriptor instead.
func (*GoalResp) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{9}
}

func (x *GoalResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GoalResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoalResp) GetTargetAmount() string {
	if x != nil {
		return x.TargetAmount
	}
	return ""
}

func (x *GoalResp) GetCurrentAmount() string {
	if x != nil {
		return x.CurrentAmount
	}
	return ""
}

func (x *GoalResp) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *GoalResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateGoalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TargetAmount string `protobuf:"bytes,2,opt,name=target_amount,json=targetAmount,proto3" json:"target_amount,omitempty"`
	Deadline     string `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
}

func (x *CreateGoalReq) Reset() {
	*x = CreateGoalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGoalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoalReq) ProtoMessage() {}

func (x *CreateGoalReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoalReq.ProtoReflect.Descriptor instead.
func (*CreateGoalReq) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{10}
}

func (x *CreateGoalReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateGoalReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGoalReq) GetTargetAmount() string {
	if x != nil {
		return x.TargetAmount
	}
	return ""
}

func (x *CreateGoalReq) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type GetGoalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetGoalReq) Reset() {
	*x = GetGoalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoalReq) ProtoMessage() {}

func (x *GetGoalReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoalReq.ProtoReflect.Descriptor instead.
func (*GetGoalReq) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{11}
}

func (x *GetGoalReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateGoalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TargetAmount  string `protobuf:"bytes,3,opt,name=target_amount,json=targetAmount,proto3" json:"target_amount,omitempty"`
	CurrentAmount string `protobuf:"bytes,4,opt,name=current_amount,json=currentAmount,proto3" json:"current_amount,omitempty"`
	Deadline      string `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
}

func (x *UpdateGoalReq) Reset() {
	*x = UpdateGoalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGoalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoalReq) ProtoMessage() {}

func (x *UpdateGoalReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoalReq.ProtoReflect.Descriptor instead.
func (*UpdateGoalReq) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateGoalReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateGoalReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGoalReq) GetTargetAmount() string {
	if x != nil {
		return x.TargetAmount
	}
	return ""
}

func (x *UpdateGoalReq) GetCurrentAmount() string {
	if x != nil {
		return x.CurrentAmount
	}
	return ""
}

func (x *UpdateGoalReq) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type DeleteGoalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DeleteGoalReq) Reset() {
	*x = DeleteGoalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGoalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGoalReq) ProtoMessage() {}

func (x *DeleteGoalReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGoalReq.ProtoReflect.Descriptor instead.
func (*DeleteGoalReq) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteGoalReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListGoalsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  string `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset string `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListGoalsReq) Reset() {
	*x = ListGoalsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGoalsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGoalsReq) ProtoMessage() {}

func (x *ListGoalsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGoalsReq.ProtoReflect.Descriptor instead.
func (*ListGoalsReq) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{14}
}

func (x *ListGoalsReq) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

func (x *ListGoalsReq) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

type ListGoalsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goals []*GoalResp `protobuf:"bytes,1,rep,name=goals,proto3" json:"goals,omitempty"`
}

func (x *ListGoalsResp) Reset() {
	*x = ListGoalsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_goal_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGoalsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGoalsResp) ProtoMessage() {}

func (x *ListGoalsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goal_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGoalsResp.ProtoReflect.Descriptor instead.
func (*ListGoalsResp) Descriptor() ([]byte, []int) {
	return file_proto_goal_proto_rawDescGZIP(), []int{15}
}

func (x *ListGoalsResp) GetGoals() []*GoalResp {
	if x != nil {
		return x.Goals
	}
	return nil
}

var File_proto_goal_proto protoreflect.FileDescriptor

var file_proto_goal_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x67, 0x6f, 0x61, 0x6c, 0x22, 0x20, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xc9, 0x01, 0x0a, 0x11, 0x42,
	0x75, 0x64, 0x67, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x45, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x45, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x22, 0x4a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x22, 0x71, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e,
	0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x6c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x71, 0x0a, 0x13, 0x47, 0x6f, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x69,
	0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x96, 0x01, 0x0a, 0x10, 0x47, 0x6f, 0x61, 0x6c, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x48, 0x0a, 0x14, 0x47, 0x6f, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e,
	0x47, 0x6f, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x56, 0x6f, 0x69,
	0x64, 0x33, 0x22, 0xbe, 0x01, 0x0a, 0x08, 0x47, 0x6f, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64,
	0x6c, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0x7d, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69,
	0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69,
	0x6e, 0x65, 0x22, 0x25, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xa4, 0x01, 0x0a, 0x0d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65,
	0x22, 0x28, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x0c, 0x4c, 0x69,
	0x73, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x35, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74,
	0x47, 0x6f, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x05, 0x67, 0x6f, 0x61,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e,
	0x47, 0x6f, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x52, 0x05, 0x67, 0x6f, 0x61, 0x6c, 0x73, 0x32,
	0xa7, 0x04, 0x0a, 0x0b, 0x47, 0x6f, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x31, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x12, 0x13, 0x2e,
	0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x12, 0x10, 0x2e,
	0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a,
	0x0e, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x31, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x12, 0x13, 0x2e,
	0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2e, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x6f, 0x61, 0x6c,
	0x12, 0x13, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x6f,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x56, 0x6f, 0x69,
	0x64, 0x33, 0x12, 0x34, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x73, 0x12,
	0x12, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47,
	0x6f, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x67, 0x6f,
	0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x63,
	0x6f, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x47, 0x6f, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x19, 0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x0c,
	0x2e, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x1b, 0x2e, 0x67,
	0x6f, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x75, 0x64, 0x67, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_goal_proto_rawDescOnce sync.Once
	file_proto_goal_proto_rawDescData = file_proto_goal_proto_rawDesc
)

func file_proto_goal_proto_rawDescGZIP() []byte {
	file_proto_goal_proto_rawDescOnce.Do(func() {
		file_proto_goal_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_goal_proto_rawDescData)
	})
	return file_proto_goal_proto_rawDescData
}

var file_proto_goal_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_goal_proto_goTypes = []any{
	(*UserId)(nil),                // 0: goal.UserId
	(*BudgetSummaryItem)(nil),     // 1: goal.BudgetSummaryItem
	(*GetUserBudgetResponse)(nil), // 2: goal.GetUserBudgetResponse
	(*GetUserMoneyRequest)(nil),   // 3: goal.GetUserMoneyRequest
	(*GetUserMoneyResponse)(nil),  // 4: goal.GetUserMoneyResponse
	(*GoalProgressRequest)(nil),   // 5: goal.GoalProgressRequest
	(*GoalProgressItem)(nil),      // 6: goal.GoalProgressItem
	(*GoalProgressResponse)(nil),  // 7: goal.GoalProgressResponse
	(*Void3)(nil),                 // 8: goal.Void3
	(*GoalResp)(nil),              // 9: goal.GoalResp
	(*CreateGoalReq)(nil),         // 10: goal.CreateGoalReq
	(*GetGoalReq)(nil),            // 11: goal.GetGoalReq
	(*UpdateGoalReq)(nil),         // 12: goal.UpdateGoalReq
	(*DeleteGoalReq)(nil),         // 13: goal.DeleteGoalReq
	(*ListGoalsReq)(nil),          // 14: goal.ListGoalsReq
	(*ListGoalsResp)(nil),         // 15: goal.ListGoalsResp
}
var file_proto_goal_proto_depIdxs = []int32{
	1,  // 0: goal.GetUserBudgetResponse.Results:type_name -> goal.BudgetSummaryItem
	6,  // 1: goal.GoalProgressResponse.results:type_name -> goal.GoalProgressItem
	9,  // 2: goal.ListGoalsResp.goals:type_name -> goal.GoalResp
	10, // 3: goal.GoalService.CreateGoal:input_type -> goal.CreateGoalReq
	11, // 4: goal.GoalService.GetGoal:input_type -> goal.GetGoalReq
	12, // 5: goal.GoalService.UpdateGoal:input_type -> goal.UpdateGoalReq
	13, // 6: goal.GoalService.DeleteGoal:input_type -> goal.DeleteGoalReq
	14, // 7: goal.GoalService.ListGoals:input_type -> goal.ListGoalsReq
	3,  // 8: goal.GoalService.GetUserSpending:input_type -> goal.GetUserMoneyRequest
	3,  // 9: goal.GoalService.GetUserIncome:input_type -> goal.GetUserMoneyRequest
	5,  // 10: goal.GoalService.GetGoalReportProgress:input_type -> goal.GoalProgressRequest
	0,  // 11: goal.GoalService.GetBudgetSummary:input_type -> goal.UserId
	9,  // 12: goal.GoalService.CreateGoal:output_type -> goal.GoalResp
	9,  // 13: goal.GoalService.GetGoal:output_type -> goal.GoalResp
	9,  // 14: goal.GoalService.UpdateGoal:output_type -> goal.GoalResp
	8,  // 15: goal.GoalService.DeleteGoal:output_type -> goal.Void3
	15, // 16: goal.GoalService.ListGoals:output_type -> goal.ListGoalsResp
	4,  // 17: goal.GoalService.GetUserSpending:output_type -> goal.GetUserMoneyResponse
	4,  // 18: goal.GoalService.GetUserIncome:output_type -> goal.GetUserMoneyResponse
	7,  // 19: goal.GoalService.GetGoalReportProgress:output_type -> goal.GoalProgressResponse
	2,  // 20: goal.GoalService.GetBudgetSummary:output_type -> goal.GetUserBudgetResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_goal_proto_init() }
func file_proto_goal_proto_init() {
	if File_proto_goal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_goal_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BudgetSummaryItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserBudgetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserMoneyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserMoneyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GoalProgressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GoalProgressItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GoalProgressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Void3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GoalResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGoalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetGoalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateGoalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteGoalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ListGoalsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_goal_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ListGoalsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_goal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_goal_proto_goTypes,
		DependencyIndexes: file_proto_goal_proto_depIdxs,
		MessageInfos:      file_proto_goal_proto_msgTypes,
	}.Build()
	File_proto_goal_proto = out.File
	file_proto_goal_proto_rawDesc = nil
	file_proto_goal_proto_goTypes = nil
	file_proto_goal_proto_depIdxs = nil
}
