version: "3.9"

services:
  migrate:
    image: "migrate/migrate"
    networks:
      - success-net
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:123321@postgres:5432/twitter_auth?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=twitter_auth

    networks:
      - success-net
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  auth:
    container_name: tweet-auth
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - success-net
    ports:
      - "8081:8081"
      - "50050:50050"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    networks:
      - success-net


networks:
  success-net:
    name: success-net
    driver: bridge

volumes:
  postgres_data:
  migrations: